apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapps.fullname" . }}-apache
spec:
  replicas: {{ .Values.apache.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "webapps.fullname" . }}-apache
  template:
    metadata:
      labels:
        app: {{ include "webapps.fullname" . }}-apache
    spec:
      containers:
        - name: apache
          image: "{{ .Values.apache.image.repository }}:{{ .Values.apache.image.tag }}"
          imagePullPolicy: {{ .Values.apache.image.pullPolicy }}
          ports:
            - containerPort: 80
